### ISSUE TITLE
Duplicate section in the apt configuration

### ISSUE THREAD

**Issue by bochecha** [ideascube/ansiblecube#35]
I get this after an `apt update` run:

```
W: Duplicate sources.list entry http://httpredir.debian.org/debian/ jessie/non-free armhf Packages (/var/lib/apt/lists/httpredir.debian.org_debian_dists_jessie_non-free_binary-armhf_Packages)
W: Vous pouvez lancer « apt-get update » pour corriger ces problèmes.
```

This is because of this line in the `/etc/apt/sources.list` file:

```
deb http://httpredir.debian.org/debian jessie non-free main contrib non-free
```

Notice how `non-free` appears twice.

Sure, that's a harmless warning.

But then, on a Koombook, it takes ~51s for `apt update` to finish. If I remove this line, I get down to `47s`. That's about 8% improvement.

Also, I'm on a fast fiber connection. I can imagine those 4 seconds start getting longer on a slower internet connection.

**Comment by letompouce** [comment]
This happens with Koombooks, thanks to a [Realtek non free firmware](https://github.com/ideascube/ansiblecube/blob/master/roles/systemInit/tasks/realtek.yml#L4-L6) we need.

Since we already mess with the `sources.list` file right [from the initial bootstrap](https://github.com/ideascube/ansiblecube/blob/master/oneClickDeploy.sh#L44), I suggest we set up a complete `sources.list` file right at this stage. Having `non-free` enabled everywhere won't hurt.

**Comment by fheslouin** [comment]
A smarter way would be to check if non-free is present then if not add it. 
That might help us from future issue ?

**Comment by bochecha** [comment]
> Having non-free enabled everywhere won't hurt.

Except for the time it takes to execute `apt update`, see the (highly unscientific) measurement in my initial comment.

**Comment by letompouce** [comment]
> A smarter way would be to check if non-free is present then if not add it.

Well that's [what we did](https://github.com/ideascube/ansiblecube/blob/master/roles/systemInit/tasks/realtek.yml#L4-L6) but it turns out we are not that smart ;^)

Instead of trying to be "smart" I would tend to "K.I.S.S.", something like:
`if arch == arm* ; then echo non-free > sources.list.d/non-free.list ; done`

> Except for the time it takes to execute `apt update`

True that. Fixed by the pseudocode example above.

**Comment by bochecha** [comment]
> Instead of trying to be "smart" I would tend to "K.I.S.S.",

How about completely removing the default `/etc/apt/sources.list` file and replacing it by a known good one?

**Comment by letompouce** [comment]
That was what I was talking in my [first comment](https://github.com/ideascube/ansiblecube/issues/35#issuecomment-246381666).

Still, we might want to not add `non-free` to all devices, so the KISS way to set up a known good `sources.list` is to replace whatever is in place at bootstrap stage (my first comment), then add `non-free` to the `arm*` ones (my second comment).

**Comment by fheslouin** [comment]
We were having an issue because of those tasks : 
- https://github.com/ideascube/ansiblecube/commit/60fbf6949b604a03e79fd035074d45c3c8476b6f#diff-f4f62a2981fcf03b810e340932aeeff0L4
- https://github.com/ideascube/ansiblecube/commit/60fbf6949b604a03e79fd035074d45c3c8476b6f#diff-dbadf07e47eec291e8b89741eaa4000dL4

And this line was executed at master run as well : https://github.com/ideascube/ansiblecube/blob/oneUpdateFile/roles/system/tasks/main.yml#L45-L48

this regex should avoid having several time the same `non-free`

```
    regexp='(jessie)\s' 
    replace='\1 non-free '
```

**Comment by letompouce** [comment]
You're trying to fix a regexp by another regexp :) And this at the ansible stage.

But we need to mess with `sources.list` right from the `oneClickDeploy.sh` stage. What about installing a complete, known, `sources.file` at this point, so we don't have to deal with it later?

If you really want to enforce this file at the `system` role stage, then why use a regexp when you can just drop a complete, known, `sources.list` again?

**Comment by fheslouin** [comment]
KoomBook and IdeasBox does not have the same source.list. So it can not be done in oneClickDeploy.sh

The regexp, fix the issue for future installation, but not for the one that have been shipped. 

So maybe we should delete all the `non-free` entry then add a proper one ?

**Comment by letompouce** [comment]
> So it can not be done in oneClickDeploy.sh

Well, we HAVE to.

As a matter of fact, you can NOT install ansible if you don't tweak `sources.list` right from the post-install. See what happens on a brand new Debian install:

```
tom@salade ~ $ ssh ideascube@debian
Warning: Permanently added 'debian,10.10.8.126' (ECDSA) to the list of known hosts.
ideascube@debian's password: 

The programs included with [...]
ideascube@debian:~$ su -
Password: 
root@debian:~# sed -i -e '/^deb cdrom/d' /etc/apt/sources.list
root@debian:~# apt-get update > /dev/null
root@debian:~# apt-get install -s python-pip git python-dev libffi-dev libssl-dev gnutls-bin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python

E: Unable to locate package python-pip
E: Package 'python-dev' has no installation candidate
E: Unable to locate package libffi-dev
root@debian:~#
```

**Comment by bochecha** [comment]
> You're trying to fix a regexp by another regexp :) And this at the ansible stage.

And now you have 4 problems!

/me runs away

**Comment by letompouce** [comment]
Ok, the Debian preseed now drops a complete, working, `sources.list` file. (https://github.com/ideascube/preseedcube/commit/fea58c504d9d5febf9e5838f9c783804d6d7e4df)

Still, this issue is about the way ansiblecube deals with this file, so let's keep it open until we double checked its behaviour.

**Comment by letompouce** [comment]
> this regex should avoid having several time the same `non-free`
> 
> ```
>     regexp='(jessie)\s' 
>     replace='\1 non-free '
> ```

Hmm, that's a part of the issue origin I guess.

As an human we are used to see the repos listed in this order: `main contrib non-free`. At least, that's the way _I_ add `non-free` when needed. When this happens (and it seems it does), this is where the `s/jessie/jessie non-free/` replacement drops a double entry.

Suggestion:

```
    regexp='(jessie main contrib$)' 
    replace='\1 non-free'
```

**Comment by fheslouin** [comment]
`oneClickDeploy.sh` is now droping a complete source list. https://github.com/ideascube/ansiblecube/blob/b4017b72fc8264ce9c5f9b33637264cbe1ada7d5/oneClickDeploy.sh#L33-L42

I will fellow the K.I.S.S way and simply drop a complete source list with AnsibleCube in order to fix the existing `source.list`. See : 163399e

**Comment by letompouce** [comment]
Should we consider this issue fixed then?

**Comment by fheslouin** [comment]
It is fixed, I close the ticket
